import axios from 'axios'

/**
 * Central Axios instance for all NeuroTree API calls.
 *
 * Multi-session architecture (F-6):
 *   X-User-ID    = stable browser/user identity (localStorage 'neurotree-user-id').
 *                  Generated once, never changes.
 *   X-Session-ID = active tree/session UUID (set per-tree by the app).
 *                  Injected by the request interceptor when activeSessionId is set.
 *
 * Backward compat: if activeSessionId is never set, only X-User-ID is sent,
 * and the backend falls back to treating X-User-ID as the session scope
 * (identical to pre-F-6 behaviour).
 */

// ── Stable User ID ────────────────────────────────────────────────────────────
// Reads the stable user UUID from localStorage.
// Migration: if the old 'neurotree-session-id' key exists but the new
// 'neurotree-user-id' key does not, migrate the old value so the user's
// existing trees are still associated with them.
function getOrCreateUserId() {
  try {
    const USER_KEY    = 'neurotree-user-id'
    const LEGACY_KEY  = 'neurotree-session-id'

    const existing = localStorage.getItem(USER_KEY)
    if (existing) return existing

    // Migrate from legacy key (single-session era)
    const legacy = localStorage.getItem(LEGACY_KEY)
    if (legacy) {
      localStorage.setItem(USER_KEY, legacy)
      return legacy
    }

    // First visit — generate a fresh stable user UUID
    const id = crypto.randomUUID()
    localStorage.setItem(USER_KEY, id)
    return id
  } catch {
    return crypto.randomUUID()
  }
}

export const USER_ID = getOrCreateUserId()

// ── Active Session ID ─────────────────────────────────────────────────────────
// Mutable ref — updated by AppContext when the user opens/creates a tree.
// Exported as an object so mutations are visible to the interceptor.
export const activeSession = { id: null }

// ── Axios Instance ────────────────────────────────────────────────────────────
const api = axios.create({
  baseURL: import.meta.env.VITE_API_URL || 'http://localhost:8000',
  timeout: 30000, // 30s — LangFlow calls can be slow
  headers: {
    'Content-Type': 'application/json',
  },
})

// Attach X-User-ID (always) and X-Session-ID (when active) to every request.
api.interceptors.request.use((config) => {
  config.headers['X-User-ID'] = USER_ID
  if (activeSession.id) {
    config.headers['X-Session-ID'] = activeSession.id
  }
  return config
})

// Global response error handler — logs full detail server-side, surfaces safe
// message to callers.
// HTTP 429 is tagged with `isRateLimit = true` so UI components can render
// a specific cooldown message instead of the generic circuit-error state.
api.interceptors.response.use(
  (response) => response,
  (error) => {
    const status = error.response?.status

    if (status === 429) {
      const retryAfter = error.response?.headers?.['retry-after']
      const err = new Error(
        'Sirkuit AI sedang cooldown (Terlalu banyak permintaan). ' +
        'Harap tunggu beberapa saat sebelum mencoba lagi.'
      )
      err.isRateLimit  = true
      err.retryAfter   = retryAfter ? parseInt(retryAfter, 10) : 30  // seconds
      console.warn('[NeuroTree] Rate limit hit — retry after', err.retryAfter, 's')
      return Promise.reject(err)
    }

    const msg =
      error.response?.data?.detail ||
      error.message ||
      'Sirkuit AI sedang mengalami gangguan sementara.'
    console.error('[NeuroTree API Error]', msg, error)
    const err = new Error(msg)
    // Preserve the HTTP status so callers can check err.status (e.g. 403 locked-node guard)
    if (status) err.status = status
    return Promise.reject(err)
  }
)

export default api

// ── Named Endpoint Helpers ─────────────────────────────────────────────────
// Centralising endpoint paths here means only one file needs updating
// when the backend API changes.

export const graphApi = {
  /** GET /api/v1/graph — lightweight node+edge list for React Flow */
  fetchGraph: () => api.get('/api/v1/graph'),

  /** GET /api/v1/node/:id — full node content for learning mode */
  fetchNode: (nodeId) => api.get(`/api/v1/node/${nodeId}`),

  /**
   * POST /api/v1/material/ingest — submit source text for AI processing.
   * F-2: treeName + learningGoal are optional; omitting them is backward compatible.
   * F-6: sessionId is the new tree's UUID (generated by NewTreeDialog); backend
   *      uses it as the session scope for the new tree.
   */
  ingest: (sourceText, treeName = '', learningGoal = '', sessionId = '') =>
    api.post('/api/v1/material/ingest', {
      source_text:   sourceText,
      tree_name:     treeName,
      learning_goal: learningGoal,
      session_id:    sessionId,
    }, { timeout: 90000 }),

  /** GET /api/v1/sessions — dashboard session history (F-2) */
  fetchSessions: () => api.get('/api/v1/sessions'),

  /**
   * PATCH /api/v1/sessions/:id — rename a tree.
   * tree_name is required; learning_goal is optional.
   */
  renameSession: (sessionId, treeName, learningGoal) =>
    api.patch(`/api/v1/sessions/${sessionId}`, {
      tree_name:     treeName,
      ...(learningGoal !== undefined ? { learning_goal: learningGoal } : {}),
    }),

  /**
   * DELETE /api/v1/sessions/:id — delete a tree and all its nodes/edges.
   */
  deleteSession: (sessionId) =>
    api.delete(`/api/v1/sessions/${sessionId}`),

  /**
   * PATCH /api/v1/sessions/:id/reveal — persist progressive reveal depth (F-8E.3).
   * Fire-and-forget: callers do not need to await the result.
   */
  updateRevealDepth: (sessionId, revealedDepth) =>
    api.patch(`/api/v1/sessions/${sessionId}/reveal`, { revealed_depth: revealedDepth }),

  /**
   * POST /api/v1/material/extract — F-4: extract plain text from a PDF or DOCX file.
   * Returns { extracted_text, char_count, truncated }.
   * The caller should pass extracted_text to graphApi.ingest().
   */
  extractFile: (file) => {
    const form = new FormData()
    form.append('file', file)
    return api.post('/api/v1/material/extract', form, {
      headers: { 'Content-Type': 'multipart/form-data' },
      timeout: 60000,
    })
  },
}

export const quizApi = {
  /** POST /api/v1/quiz/generate */
  generate: (nodeId) =>
    api.post('/api/v1/quiz/generate', { node_id: nodeId }),

  /**
   * POST /api/v1/quiz/evaluate
   * F-7C: question_index (0|1|2) is required for the 3-question session loop.
   * Default 0 keeps backward compat for any caller that doesn't pass it.
   */
  evaluate: (nodeId, userAnswer, questionIndex = 0) =>
    api.post('/api/v1/quiz/evaluate', {
      node_id:        nodeId,
      user_answer:    userAnswer,
      question_index: questionIndex,
    }),

  /** GET /api/v1/quiz/recommend */
  recommend: () => api.get('/api/v1/quiz/recommend'),
}

export const careerApi = {
  /** POST /api/v1/career/pathway */
  pathway: (careerGoal) =>
    api.post('/api/v1/career/pathway', { career_goal: careerGoal }),
}

export const masterLightApi = {
  /**
   * POST /api/v1/master-light/generate
   * Generates a Master Light assessment question for the given master_light node.
   * Returns { node_id, question }
   */
  generate: (nodeId) =>
    api.post('/api/v1/master-light/generate', { node_id: nodeId }),

  /**
   * POST /api/v1/master-light/evaluate
   * Evaluates user's answer and returns master_light_mastery score.
   * question_index: 0 | 1 | 2 (3-question session)
   * Returns { ai_score, feedback, master_light_mastery, is_final, question_index }
   */
  evaluate: (nodeId, userAnswer, questionIndex = 0) =>
    api.post('/api/v1/master-light/evaluate', {
      node_id:        nodeId,
      user_answer:    userAnswer,
      question_index: questionIndex,
    }),
}
